### PR TITLE
Add ES Day 2 Example Content

### PR DESCRIPTION
**Pull request by jtracey93**
Adding Diagrams and content to ES Day 2 Example page

### CODE REVIEW

**Review by richeney — APPROVED** [review]
lgtm. I'll check with @jasoncabot-ms why the Actions failed.

**Comment by jasoncabot-ms** [comment]
I just kickd off another run of the build - looks like a temporary failure :)

**Comment by jasoncabot-ms** [comment]
Ah - no it's failing because the PR is from a forked repo which doesn't have access to the API key for deployment

**Comment by jasoncabot-ms** [comment]
This is the issue preventing https://github.com/Azure/static-web-apps/issues/1

**Pull request merged**
