### PR TITLE
Added Policy, Automation, Log Analytics challenges

### PR DESCRIPTION
**Pull request by lufussel**
Added 2 additional pages. 

Challenge: Azure Policy
- Create Log Analytics workspace
- Azure Policy to deploy Log Analytics agent to Azure Arc VMs
- Azure Policy to inherit tags

Challenge: Management baseline
- Create an Automation account
- Enable Update Management
- Enable Inventory
- Query with Log Analytics

### CODE REVIEW

**Comment by lufussel** [comment]
@richeney please review. Thanks!

**Comment by jasoncabot-ms** [comment]
@lufussel did you get the option to create a branch in the azurecitadel repo directly rather than creating a fork? That's why this PR is failing because it's unable to deploy a staging version of the static web app from a pull request originating from a fork (for security)

**Comment by richeney** [comment]
@jasoncabot-ms That would be my fault - I'm telling people to fork, clone, branch. 

What is the flow if you clone direct and create a branch? Is that actually the default and I've been doing it wrong for a couple of years?

**Review by richeney — APPROVED** [review]
lgtm - two new files so very safe!!

**Pull request merged**
